# Generated by Django 5.1.4 on 2025-07-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed'), ('approved', 'Approved')], default='assigned', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='task_attachments/')),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
