# Generated by Django 5.1.4 on 2025-07-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timeline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
